name: Terraform Deploy on PR Approval

on:
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the `main` branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.0'

      # Step 3: Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'ap-south-1'

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Plan Terraform deployment
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 7: Wait for PR Approval
      - name: Check for PR Approval
        id: check_approval
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Apply Terraform changes only after approval
      - name: Terraform Apply
        if: ${{ steps.check_approval.outputs.approved == 'true' }}
        run: terraform apply -auto-approve tfplan
